Big Update!

diff --git a/profile/airootfs/etc/skel/.local/bin/wpgtk b/profile/airootfs/etc/skel/.local/bin/wpgtk
--- a/profile/airootfs/etc/skel/.local/bin/wpgtk
+++ b/profile/airootfs/etc/skel/.local/bin/wpgtk
@@ -9,21 +9,26 @@
 
 # Color files
 config="$HOME/.config"
+config_file="$HOME/.theme"
 alacritty="$config/alacritty/colors.toml"
 polybar="$config/polybar/colors.ini"
 rofi="$config/rofi/themes/colors.rasi"
-discord="$config/Vencord/themes/theme.css"
+discord="$config/Equicord/themes/caelestia.theme.css"
 dunst="$config/dunst/dunstrc"
 geany="$config/geany/colorschemes/Pywal.conf"
 copyq="$config/copyq/copyq.conf"
 jgmenu="$config/jgmenu/jgmenurc"
 spotify="$config/spicetify/Themes/pywal/color.ini"
-eww="$config/eww/colors.scss"
 hypr="$config/hypr/colors.conf"
-swaync="$config/swaync/style.css"
-waybar="$HOME/.config/waybar/colors.css"
+kde="$config/kdeglobals"
+sniffnet="$config/sniffnet/colors.toml"
 Wallpapers="$HOME/Pictures/Wallpapers"
-alpha='FF'
+
+if [[ -f "$config_file" ]]; then
+	source "${config_file}"
+else
+	echo -e "# wpgtk config file\ntransparency='false'" > "${config_file}"
+fi
 
 ## Change colors
 change_colors(){
@@ -113,7 +118,21 @@ change_colors(){
 		-e "s/error_red=.*/error_red=${magenta}/g" \
 		-e "s/current_line_grey=.*/current_line_grey=${bg_lighter}/g" \
 		-e "s/selection_blue=.*/selection_blue=${white}/g"
-		
+	
+	if [[ -f "$hypr" ]]; then 
+	# hypr	
+	cat > "$hypr" <<- EOF 
+	\$black		= rgba(${black:1}aa)
+	\$red 		= rgba(${red:1}ff)
+	\$green		= rgba(${green:1}ff)
+	\$yellow 	= rgba(${yellow:1}ff)
+	\$blue 		= rgba(${blue:1}ff)
+	\$magenta 	= rgba(${magenta:1}ff)
+	\$cyan 		= rgba(${cyan:1}ff)
+	\$white     	= rgba(${white:1}ff)
+	EOF
+	fi
+	
 	# copyq 
 	sed -i "$copyq" \
 		-e "s/bg=#.*/bg=${background}/g" \
@@ -136,7 +155,17 @@ change_colors(){
 		-e "s/color_sel_bg         = .*/color_sel_bg         = ${bright_black} 40/g" \
 		-e "s/color_sel_fg         = .*/color_sel_fg         = ${bright_red} 100/g" \
 		-e "s/color_sep_fg         = .*/color_sep_fg         = ${bright_blue} 40/g"
-	
+
+	# sniffnet
+		cat > "$sniffnet" <<- EOF
+		primary= "${bg_mix}"
+		secondary= "${bright_black}"
+		outgoing= "${bright_red}"
+		text_body= "${foreground}"
+		text_headers= "${bright_blue}"
+		starred= "${bright_yellow}"
+		EOF
+
 	# zathura and sioyek
 	reader-colors
 
@@ -152,6 +181,8 @@ change_colors(){
 		-e "s/--accent-3: .*/--accent-3: ${blue};/g" \
 		-e "s/--accent-4: .*/--accent-4: ${yellow};/g" \
 		-e "s/--accent-5: .*/--accent-5: ${magenta};/g" \
+		-e "s/--bg-1: .*/--bg-1: ${bg_light};/g" \
+		-e "s/--bg-2: .*/--bg-2: ${background};/g" \
 		-e "s/--bg-3: .*/--bg-3: ${bg_light};/g" \
 		-e "s/--bg-4: .*/--bg-4: ${bg_mix};/g"
 	fi 
@@ -180,60 +211,70 @@ change_colors(){
 	notification-error = ${bright_red:1}
 	equalizer          = ${white:1}
 	misc               = ${red:1}
+	_EOF_
+	fi
+	
+	if [[ -f "$kde" ]]; then 
+	cat > "$kde" <<- EOF	
+	[Colors:Selection]
+	BackgroundNormal=$background
+	ForegroundActive=$foreground
+	ForegroundInactive=$bg_light
+	ForegroundNegative=$yellow
+	
+	[Colors:View]
+	BackgroundAlternate=$bg_light
+	BackgroundNormal=$bg_mix
+	DecorationFocus=$red
+	DecorationHover=$yellow
+	ForegroundActive=$foreground
+	ForegroundInactive=$bright_white
+	ForegroundLink=$red
+	ForegroundNegative=$background
+	ForegroundNeutral=$foreground
+	ForegroundNormal=$foreground
+	ForegroundPositive=$green
+	ForegroundVisited=$blue
 	EOF
 	fi
-
-	# eww
-	if [[ -f "$eww" ]]; then 
-	[[ "$alpha" == "FF" ]] &&  sed -i "s/\$alpha: 0.3/\$alpha: 1.0/" "$eww" \
-	|| sed -i "s/\$alpha: 1.0/\$alpha: 0.3/" "$eww" 
-	sed -i 	"$eww" \
-		-e "s/\$background: #.*/\$background: ${bg_light};/g" \
-		-e "s/\$bg-alt: #.*/\$bg-alt: ${background};/g" \
-		-e "s/\$fg: #.*/\$fg: ${foreground};/g" \
-		-e "s/\$fg-alt: #.*/\$fg-alt: $white;/g" \
-		-e "s/\$red: #.*/\$red: $bright_red;/g" \
-		-e "s/\$green: #.*/\$green: $bright_green;/g" \
-		-e "s/\$yellow: #.*/\$yellow: $bright_yellow;/g" \
-		-e "s/\$blue: #.*/\$blue: $bright_blue;/g" \
-		-e "s/\$purple: #.*/\$purple: $bright_magenta;/g" \
-		-e "s/\$cyan: #.*/\$cyan: $bright_cyan;/g" \
-		-e "s/\$gray: #.*/\$gray: $bright_black;/g" \
-		-e "s/\$gray-alt: #.*/\$gray-alt: $bright_black;/g"
-	fi
-
-	if [[ -f "$hypr" ]]; then 
-	# hypr
-	cat > "$hypr" <<- EOF 
-		\$black		= ${bright_black:1}aa
-		\$red 		= ${bright_red:1}ff
-		\$green		= ${bright_green:1}ff
-		\$yellow 	= ${bright_yellow:1}ff
-		\$blue 		= ${bright_blue:1}ff
-		\$magenta 	= ${bright_magenta:1}ff
-		\$cyan 		= ${bright_cyan:1}ff
-		\$white     	= ${bright_white:1}ff
-		EOF
-	fi
-
+	
 	# resize and move wallpaper for use by other programs
-	ln -s "$wallpaper" "$HOME"/.config/wpg/wallpapers/ &> /dev/null
+	ln -sf "$wallpaper" "$HOME"/.config/wpg/wallpapers/
+}
+
+qt_colors(){
+	material
+	python "$config/Kvantum/Colloid/changeAdwColors.py" &> /dev/null
+}
+
+toggle_transparency(){
+	if [[ "$transparency" == "true" ]]; then 
+		sed -i "s/transparency=.*/transparency='false'/" "$config_file"
+		transparency='false'
+	else
+		sed -i "s/transparency=.*/transparency='true'/" "$config_file"
+		transparency='true'
+	fi
+	change_colors
 }
 
 transparent(){
-	if [[ "$alpha" == "FF" ]]; then 
+	if [[ "$transparency" == "false" ]]; then 
 		sed -i "s/opacity =.*/opacity = 1.0/" "${alacritty%/*}/alacritty.toml"
 		sed -i "s/frame_width = .*/frame_width = 0/" "$dunst"
+		sed -i "/^[^#]*opacity/s/^/#/" "$HOME"/.config/hypr/hyprland.conf
 		alpha_jg="100"
 		alpha_rofi="ff"
-		alpha_dunst="ff"
+		alpha_dunst="ff" 
 	else 
 		sed -i "s/opacity =.*/opacity = 0.75/" "${alacritty%/*}/alacritty.toml"
 		sed -i "s/frame_width = .*/frame_width = 3/" "$dunst"
-		alpha_jg="$alpha"
-		alpha_rofi="$alpha"
+		sed -i "/opacity/s/^#//" "$HOME"/.config/hypr/hyprland.conf
+		alpha_jg="70"
+		alpha_rofi="70"
 		alpha_dunst="99"
 	fi
+	sed -i "s/\"transparency\": [^,]*/\"transparency\": $transparency/" "$HOME/.config/illogical-impulse/config.json"
 }
 
 # this functions should only be used if you have a system with a seperate home partition 
@@ -305,14 +346,15 @@ wall() {
 		elif [[ "$XDG_SESSION_TYPE" == "wayland" ]]; then
             swww query || swww-daemon -q & disown
 			swww img "$wall" \
-				--transition-fps 60 \
-			    --transition-type any \
-			    --transition-duration 2 & disown
+				--transition-step 120 \
+				--transition-fps 120 \
+				--transition-type random \
+				--transition-duration 1 & disown
 	    fi
     fi
 
-    wpg -A "$wall" && wpg -s "$wall"
-    rm "${wall}_wal_sample.png"
+	wpg -A "$wall" && wpg -s "$wall"
+	rm "${wall}_wal_sample.png"
     exit
 }
 
@@ -323,11 +365,13 @@ restore() {
 	elif [[ "$XDG_SESSION_TYPE" == "wayland" ]]; then
 		swww query || swww-daemon -q & disown
 		if [[ "$(swww query | awk '{print $8}')" != "$wallpaper" ]]; then
-		main &
+		#main &
 		swww img "$wallpaper" \
-			--transition-fps 60 \
+			--transition-step 100 \
+			--transition-fps 120 \
+			--transition-angle 30 \
 			--transition-type any \
-			--transition-duration 2 & disown
+			--transition-duration 1 & disown
 		fi
     fi
 }
@@ -339,33 +383,35 @@ setup(){
 	done
 }
 
+# Set Random Wallpaper from ~/Pictures/Wallpaper
 random(){
 	if [[ "$(ls -A $Wallpapers)" ]]; then 
-        if command -v waypaper >/dev/null 2>&1; then
-			waypaper --random
-		else
+        #if command -v waypaper >/dev/null 2>&1; then
+		#	waypaper --random
+		#else
             image="$(find "$Wallpapers" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \) -exec shuf -ezn 1 {} + | xargs -0)"
             wall "$image"
-        fi
+        #fi
 	else
 		notify-send -u low -r 43 "No Wallpapers Were Found in:" "~/Pictures/Wallpapers"
 	fi
 }
 
-# this function uses nsxiv or waypaper as wallpaper selector for wpg 
-# to set a wallpaper in nsxiv you should select a wallpaper by pressing "m" and then quitting 
-pick(){
-	if [[ "$(ls -A $Wallpapers)" ]]; then 
-		if command -v waypaper >/dev/null 2>&1; then
-			waypaper
-		else
-			wal=$(nsxiv -torb $Wallpapers)
-			wall "$wal"
-		fi
-	else
-		notify-send -u low -r 43 "No Wallpapers Were Found In:" "~/Pictures/Wallpapers"
+# This function uses nsxiv or waypaper as a wallpaper selector for wpg.
+# To set a wallpaper in nsxiv, select a wallpaper by pressing "m" and then quitting.
+pick() {
+	if [[ -z "$(ls -A "$Wallpapers" 2>/dev/null)" ]]; then
+		notify-send -u low -r 43 "No Wallpapers Found" "$Wallpapers"
+		return 1
 	fi
-}	
+
+	if command -v waypaper >/dev/null 2>&1; then
+		[[ -z $(pgrep waypaper) ]] && waypaper || echo "Chill!"
+	else
+		wal=$(nsxiv -torb "$Wallpapers") || return 1
+		[[ -n "$wal" ]] && wall "$wal"
+	fi
+}
 
 dynamic(){
 	dynmaic_wall="$HOME/Pictures/Dynamic"
@@ -412,22 +458,24 @@ misc(){
 		conky.sh restart &
 		"$HOME/.config/polybar/launch.sh" &> /dev/null &
 		[[ "$XDG_CURRENT_DESKTOP" == "bspwm" ]] && "$HOME"/.config/bspwm/bsp-border &
-	elif [[ "$XDG_SESSION_TYPE" == "wayland" ]]; then
-		# ags
-		if [[ -d "$HOME/.config/ags/scss/" ]]; then
-			"$HOME"/.config/ags/scripts/color_generation/colorgen.sh "$wallpaper" --apply --smart >/dev/null 2>&1
+	elif [[ "$XDG_SESSION_TYPE" == "wayland" ]]; then	
+		# Quickshell
+		if [[ -n $(pgrep -f "qs|quickshell") ]]; then
+			ln -sf "$HOME"/.cache/wal/colors-qs.json "$HOME"/.local/state/quickshell/user/generated/colors.json
+			"$HOME"/.config/quickshell/scripts/least_busy_region.py --screen-width "1920" \
+				--screen-height "1080" --width 300 --height 200 \
+				"$wallpaper" > "$HOME"/.local/state/quickshell/user/generated/wallpaper/least_busy_region.json &
 	    fi
 	    
 		gsettings set org.gnome.desktop.interface gtk-theme "Dummy"
 		gsettings set org.gnome.desktop.interface gtk-theme "FlatColor"
-		gsettings set org.gnome.desktop.interface color-scheme prefer-dark
-		gsettings set org.gnome.desktop.interface color-scheme prefer-light
 	fi
 }
 
 partial(){
 	change_colors
 	misc
+	qt_colors
 	pkill dunst; dunst > /dev/null 2>&1 & disown
 	check spicetify -q refresh &
 	check pywalfox update >/dev/null 2>&1 &
@@ -446,51 +494,146 @@ main(){
 
 ## Check if wpg is installed and get colors
 run(){
-	if [[ -f "/usr/bin/wpg" ]]; then
-		## check if the files exists and import colors from wpg
-		if [[ -f "$HOME/.cache/wal/colors.sh" ]]; then
-			source "$HOME/.cache/wal/colors.sh"
-			# Normal colors
-			background="$(printf "%s\n" "$background")"
-			foreground="$(printf "%s\n" "$foreground")"
-			black="$(printf "%s\n" "$color0")"
-			red="$(printf "%s\n" "$color1")"
-			green="$(printf "%s\n" "$color2")"
-			yellow="$(printf "%s\n" "$color3")"
-			blue="$(printf "%s\n" "$color4")"
-			magenta="$(printf "%s\n" "$color5")"
-			cyan="$(printf "%s\n" "$color6")"
-			white="$(printf "%s\n" "$color7")"
-			# Bright colors
-			bright_black="$(printf "%s\n" "$color8")"
-			bright_red="$(printf "%s\n" "$color9")"
-			bright_green="$(printf "%s\n" "$color10")"
-			bright_yellow="$(printf "%s\n" "$color11")"
-			bright_blue="$(printf "%s\n" "$color12")"
-			bright_magenta="$(printf "%s\n" "$color13")"
-			bright_cyan="$(printf "%s\n" "$color14")"
-			bright_white="$(printf "%s\n" "$color15")"
-			# Additional colors
-			bg_mix="$(pastel mix -f 0.4 $bright_black $black | pastel format hex)"
-			bg_light="$(pastel mix -f 0.2 $bright_black $black | pastel format hex)"
-			bg_lighter="$(pastel lighten 0.08 $black | pastel format hex)"
-			bg_dark="$(pastel darken 0.02 ${background:1} | pastel format hex)"
-			bg_rgb="$(pastel format rgb ${bg_mix:1})"
-			bg_mix_rgb="$(pastel format rgb ${bg_mix:1})"
-			## merging the Xresources files with the main one
-			xrdb -merge "$HOME"/.cache/wal/colors.Xresources
-		else
-			echo "[!] Theme file not found"
-			exit 1
-		fi 
-	else
+	if [[ ! -f "/usr/bin/wpg" ]]; then
 		echo "[!] 'wpgtk' is not installed."
 		echo "Installing from the AUR..." 
-		yay -S wpgtk-git --noconfirm
-		wpgConfig
-		# this command installs rofi, gtk, and openbox themes
+		yay -S wpgtk --noconfirm
+		# this command installs gtk, and openbox themes
 		wpg-install.sh -g -o
 	fi
+
+	# Normal colors
+	background="$(printf "%s\n" "$background")"
+	foreground="$(printf "%s\n" "$foreground")"
+	black="$(printf "%s\n" "$color0")"
+	red="$(printf "%s\n" "$color1")"
+	green="$(printf "%s\n" "$color2")"
+	yellow="$(printf "%s\n" "$color3")"
+	blue="$(printf "%s\n" "$color4")"
+	magenta="$(printf "%s\n" "$color5")"
+	cyan="$(printf "%s\n" "$color6")"
+	white="$(printf "%s\n" "$color7")"
+	# Bright colors
+	bright_black="$(printf "%s\n" "$color8")"
+	bright_red="$(printf "%s\n" "$color9")"
+	bright_green="$(printf "%s\n" "$color10")"
+	bright_yellow="$(printf "%s\n" "$color11")"
+	bright_blue="$(printf "%s\n" "$color12")"
+	bright_magenta="$(printf "%s\n" "$color13")"
+	bright_cyan="$(printf "%s\n" "$color14")"
+	bright_white="$(printf "%s\n" "$color15")"
+	# Additional colors
+	bg_mix="$(pastel mix -f 0.4 $bright_black $black | pastel format hex)"
+	bg_light="$(pastel mix -f 0.2 $bright_black $black | pastel format hex)"
+	bg_lighter="$(pastel lighten 0.08 $black | pastel format hex)"
+	bg_dark="$(pastel darken 0.02 ${background:1} | pastel format hex)"
+
+	#bg=$(pastel mix -f 0.2 "$black" "$bright_black" | pastel format hex) # 20%
+	
+	#bg_mix=$(pastel mix -f 0.8 "$black" "$bright_black" | pastel format hex) # 80%
+	#bg_dark=$(pastel mix -f 0.45 "$black" "$bright_black" | pastel format hex) # Darken 10%
+	#bg_darker=$(pastel mix -f 0.4 "$color0" "$color8" | pastel format hex) # 40%
+
+	#bg_light=$(pastel lighten 0.1 "$black" | pastel format hex) # Lighten 10%
+	#bg_lighter=$(pastel lighten 0.2 "$black" | pastel format hex) # Lighten 20%
+	
+	#fg_mix=$(pastel mix -f 0.3 "$color7" "$color15" | pastel format hex) # 30%
+	#fg_light=$(pastel lighten 0.2 "$color5" | pastel format hex) # Lighten 20%
+	
+	bg_rgb="$(pastel format rgb ${bg_mix:1})"
+	bg_mix_rgb="$(pastel format rgb ${bg_mix:1})"
+	
+	## merging the Xresources files with the main one
+	xrdb -merge "$HOME"/.cache/wal/colors.Xresources
+
 }
 
-"$@"
+help(){
+    echo "Usage: ${0##*/} [options]"
+    echo "Options:"
+    echo "  -h, --help       Show this help message and exit"
+    echo "  --restore        Restore previous wallpaper"
+    echo "  --random         Set a random wallpaper"
+    echo "  --set            Set a specific wallpaper"
+    echo "  --pick           Pick a wallpaper manually"
+    echo "  --phone          Set a phone wallpaper"	
+    echo "  --reload         Reload colors"	
+    echo "  --restart        Restart apps and reload colors"	
+}
+
+# Source theme file
+if [[ -f "$HOME/.cache/wal/colors.sh" ]]; then
+	source "$HOME/.cache/wal/colors.sh"
+else
+	echo "[!] Theme file not found"
+	exit 1
+fi
+
+case "$1" in
+	-h|--help)
+		help
+		;;
+	--run)
+		run
+		exit 0
+		;;
+	--restore)
+		restore
+		exit 0
+		;;
+	--random)
+		random
+		exit 0
+		;;
+	--purge)
+		rm "$wallpaper"
+		random
+		exit 0
+		;;
+	--set)
+		wall "$2"
+		exit 0
+		;;
+	--pick)
+		pick
+		exit 0
+		;;
+	--phone)
+		phone
+		exit 0
+		;;
+	--colors)
+		run
+		exit 0
+		;;
+	--trans)
+		toggle_transparency
+		exit 0
+		;;
+	--material)
+		material
+		exit 0
+		;;
+	--apply)
+		change_colors
+		exit 0
+		;;
+	--lock)
+		lockPerms
+		exit 0
+		;;
+	--reload)
+		partial
+		exit 0
+		;;
+	--restart)
+		main
+		exit 0
+		;;
+	*)
+		echo "Unknown option: $1"
+		help
+		;;
+esac
+
+#"$@"
